// skills actions

export const SEARCH_SKILLS_REQUEST = 'SEARCH_SKILLS_REQUEST';
export const SEARCH_SKILLS_FAILURE = 'SEARCH_SKILLS_FAILURE';
export const SEARCH_SKILLS_SUCCESS = 'SEARCH_SKILLS_SUCCESS';
export const CHANGE_SEARCH_FIELD   = 'CHANGE_SEARCH_FIELD';

// main-details actions

export const SERVICES_REQUEST = 'SERVICES_REQUEST';
export const SERVICES_FAILURE = 'SERVICES_FAILURE';
export const SERVICES_SUCCESS = 'SERVICES_SUCCESS';
export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_FAILURE = 'SERVICE_DETAIL_FAILURE';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';

//  news-feed actions

export const NEWS_REQUEST = 'NEWS_REQUEST';
export const NEWS_FAILURE = 'NEWS_FAILURE';
export const NEWS_SUCCESS = 'NEWS_SUCCESS';
export const PREVIOUS_NEWS_REQUEST = 'PREVIOUS_NEWS_REQUEST';
export const PREVIOUS_NEWS_FAILURE = 'PREVIOUS_NEWS_FAILURE';
export const PREVIOUS_NEWS_SUCCESS = 'PREVIOUS_NEWS_SUCCESS';